name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
    # Once every Sunday at midnight UTC
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://www.mrdemonwolf.com/feed/
          committer_email: natanial.henniges@mrdemonwolf.com
          committer_username: NathanialHenniges
          template: '<li><a href="$url?utm_source=github&utm_medium=profile-readme&utm_campaign=blog-section&utm_content=blog-listings">$title</a></li>$newline'
